#### Image Classification 
##### Task2 : Machine Learning
##### Student: Jun Wee Tan 101231636

In [19]:
import numpy as np
import pickle

#import matplotlib.pyplot as plt


In [20]:
#function to load and serialize the CIFAR-10 dataset files
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [9]:
# dataset checking and preparation
batch_list = []

#import all 5 data batches of image
for i in range (1,6):  
    db = unpickle(f'data_batch_{i}')
    batch_list.append(db)

#checking
for index, batch  in enumerate(batch_list):
    print(f"Data Batch {index + 1} length: ", len(batch))
    print(f"Data Batch {index + 1} keys: ", batch.keys())
    print(f"Data Batch {index + 1} data file type:", batch[b'data'].dtype)
    print(f"Data Batch {index + 1} data file shape:", batch[b'data'].shape)
    print()
    
batch_list[0][b'data']

Data Batch 1 length:  4
Data Batch 1 keys:  dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
Data Batch 1 data file type: uint8
Data Batch 1 data file shape: (10000, 3072)

Data Batch 2 length:  4
Data Batch 2 keys:  dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
Data Batch 2 data file type: uint8
Data Batch 2 data file shape: (10000, 3072)

Data Batch 3 length:  4
Data Batch 3 keys:  dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
Data Batch 3 data file type: uint8
Data Batch 3 data file shape: (10000, 3072)

Data Batch 4 length:  4
Data Batch 4 keys:  dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
Data Batch 4 data file type: uint8
Data Batch 4 data file shape: (10000, 3072)

Data Batch 5 length:  4
Data Batch 5 keys:  dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
Data Batch 5 data file type: uint8
Data Batch 5 data file shape: (10000, 3072)



array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144],
       [255, 253, 253, ...,  83,  83,  84],
       ...,
       [ 71,  60,  74, ...,  68,  69,  68],
       [250, 254, 211, ..., 215, 255, 254],
       [ 62,  61,  60, ..., 130, 130, 131]], dtype=uint8)

In [10]:
#display image 
def plot_images(images, labels, num_images):
    fig, axes = plt.subplots(1, num_images, figsize=(10, 2)) #create subplot with 1 row and 5 column
    for i, ax in enumerate(axes):
        ax.imshow(images[i])
        ax.set_title(f"Label/Catg: {labels[i]}")
        ax.axis('off') 
    plt.show()

for batch in batch_list:
    #reshape data from flatten array 10000x3072 to 10000x32x32x3 RGB images
    images_reshaped = batch[b'data'].reshape(10000, 3, 32, 32).transpose(0, 2, 3, 1) #transpose into (10000x32x32x3) position
    labels = batch[b'labels']
    #plot_images(images_reshaped, labels, num_images=5) #show 5 image

#### Data preparation

In [13]:
#min-max normalisation 
#normalise pixel values from [0,255] to [0, 1] in each data batch
for index, batch in enumerate(batch_list):
    #changed float to float32 to alleviate memory issues : Michael
    batch[b'data'] = batch[b'data'].astype(float) / 255
    print(f"Min for batch{index+1}: {np.min(batch[b'data'])}")
    print(f"Max for batch{index+1}: {np.max(batch[b'data'])}")
    print()

#flatten
#reshape each data batch
for batch in batch_list:
    batch[b'data'] = batch[b'data'].reshape(10000, 3072)  # Flatten the images back to 2D array

#standardization 
#re-scales the data_batch to have the mean 0 and std 1
from sklearn.preprocessing import StandardScaler

#combine all 5 training data_batch into single array 
arrayX = [] 
arrayY = []
for batch in batch_list:
    arrayX.append(batch[b'data'])
    arrayY.append(batch[b'labels'])

#merge 5 array into single array
#Commented out to stop memory issues
#X_train = np.concatenate(arrayX, axis=0)
#y_train = np.concatenate(arrayY, axis=0)
#print(X_train.shape, y_train.shape)

#Temporary Training Batch - Michael
X_train = batch_list[0][b'data']
y_train = batch_list[0][b'labels']
X_train = np.array(X_train)
y_train = np.array(y_train)
print(X_train.shape, y_train.shape)
#initialize
scaler = StandardScaler()

#train
scaler.fit(X_train)

#transform
std_X_train = scaler.transform(X_train)
print("Mean of scaled training data (should be close to 0):", np.mean(std_X_train))
print("Standard deviation of scaled training data (should be close to 1):", np.std(std_X_train))




Min for batch1: 0.0
Max for batch1: 1.5378700499807765e-05

Min for batch2: 0.0
Max for batch2: 1.5378700499807765e-05

Min for batch3: 0.0
Max for batch3: 1.5378700499807765e-05

Min for batch4: 0.0
Max for batch4: 1.5378700499807765e-05

Min for batch5: 0.0
Max for batch5: 1.5378700499807765e-05

(10000, 3072) (10000,)
Mean of scaled training data (should be close to 0): -4.2142770754575546e-16
Standard deviation of scaled training data (should be close to 1): 0.9999999999999998


In [ ]:
###Transform and fit the rest of the batches
#Other batches - Michael
X_train_b1 = batch_list[1][b'data']
y_train_b1 = batch_list[1][b'labels']
X_train_b1 = np.array(X_train_b1)
y_train_b1 = np.array(y_train_b1)
print(X_train_b1.shape, y_train_b1.shape)
#initialize

#train
scaler.fit(X_train_b1)

#transform
std_X_train_b1 = scaler.transform(X_train_b1)
print("Mean of scaled training data (should be close to 0):", np.mean(std_X_train_b1))
print("Standard deviation of scaled training data (should be close to 1):", np.std(std_X_train_b1))

X_train_b2 = batch_list[2][b'data']
y_train_b2 = batch_list[2][b'labels']
X_train_b2 = np.array(X_train_b2)
y_train_b2 = np.array(y_train_b2)
print(X_train_b2.shape, y_train_b2.shape)
#initialize

#train
scaler.fit(X_train_b2)

#transform
std_X_train_b2 = scaler.transform(X_train_b2)
print("Mean of scaled training data (should be close to 0):", np.mean(std_X_train_b2))
print("Standard deviation of scaled training data (should be close to 1):", np.std(std_X_train_b2))

X_train_b3 = batch_list[3][b'data']
y_train_b3 = batch_list[3][b'labels']
X_train_b3 = np.array(X_train_b3)
y_train_b3 = np.array(y_train_b3)
print(X_train_b3.shape, y_train_b3.shape)

#train
scaler.fit(X_train_b3)

#transform
std_X_train_b3 = scaler.transform(X_train_b3)
print("Mean of scaled training data (should be close to 0):", np.mean(std_X_train_b3))
print("Standard deviation of scaled training data (should be close to 1):", np.std(std_X_train_b3))



#### Learning type of problem: 
* Image Classification based on image pixel feature with Machine Learning
#### Machine Learning algorithm: Support Vector Machine (SVM)

In [18]:
### DUMP MODEL - Michael M
###Gonna dump the model so you guys don't have to retrain it and destroy your laptops CPUs.
load = True


#https://stackoverflow.com/questions/56107259/how-to-save-a-trained-model-by-scikit-learn
if load:
    with open('svmModel.pkl', 'rb') as file:
        svm_model = pickle.load(file)

In [14]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

print("Training features shape:", std_X_train.shape)
print("Training labels shape:", y_train.shape)

#split the data into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(std_X_train, y_train, test_size=0.2, random_state=42)

#initial
print("Initializing the SVM...")

#If model hasn't been loaded, create new model
if load == False:
    #n_jobs = -1 means use all availible cores. You may want to change this ahaha.
    svm_model = svm.SVC(kernel='linear', n_jobs=-1)

#train
print("Training the model...")
svm_model.fit(X_train, y_train)

# Predictions
print("Making predictions...")
y_pred = svm_model.predict(X_test)

# Performance
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Validation Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

Training features shape: (10000, 3072)
Training labels shape: (10000,)
Initializing the SVM...
Training the model...
Making predictions...
Validation Accuracy: 0.3055
Confusion Matrix:
 [[ 80  10  27   6   7   7   6   8  43  13]
 [ 22  79  20  11   8   8   7  16  15  27]
 [ 15  17  50  23  32  12  14  15  15   4]
 [ 22  12  23  55  15  31  17  13   8   3]
 [ 14   7  44  21  49  27  23  13   5   2]
 [ 12  17  21  38  25  32  10   8   8   6]
 [  6   4  34  35  30  21  40   8   7   2]
 [ 18  13  31  17  18   9   9  71   7   7]
 [ 41  20  12   9  10   8   3   6 104  11]
 [ 25  41  11  11   9  10   7  10  16  51]]


In [17]:
### DUMP MODEL - Michael M
###Gonna dump the model so you guys don't have to retrain it and destroy your laptops CPUs.
dump = False
###Change dump to True if you want to save the model since you've done extra training

#https://stackoverflow.com/questions/56107259/how-to-save-a-trained-model-by-scikit-learn
if dump:
    with open('svmModel.pkl', 'wb') as file:
        pickle.dump(svm_model, file)


In [21]:
#### Image Classification - Model Trraining
##### Task2 : Machine Learning
##### Student: Michael Mooney 104266194
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler

testSVM = True
#Maybe make a pipelinbe here just for my sanity
pipelineSVM = Pipeline(
    [   
        ('clf', svm_model)
    ]
)
skfSVM = StratifiedKFold(n_splits=10)

if testSVM:
    params = {
    'clf__kernel':['linear', 'rbf', 'poly'],
    'clf__gamma':[0.01, 0.10, 0.5, 1,2,3],
    'clf__C':[0.01, 0.1, 0.5, 1,2,3]
    }
    
    grid = GridSearchCV(
        pipelineSVM, 
        params, 
        cv = skfSVM, 
        refit = True, 
        verbose = 3, 
        n_jobs=-1, 
        error_score='raise'
    )
    grid.fit(
        X_train, 
        y_train
            )
     
    gridPred = grid.predict(X_test) 

    print(pipelineSVM.get_params().keys())
    print(grid.best_params_)
    print(grid.best_estimator_)
    print(classification_report(y_test, gridPred)) 

Fitting 10 folds for each of 108 candidates, totalling 1080 fits


In [ ]:
#### PIPELINE - RFC_CLF
from sklearn.ensemble import RandomForestClassifier

clf_RFC = RandomForestClassifier(random_state=37)